// <auto-generated />
namespace Shop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Integrated_ASPNET_Identity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Integrated_ASPNET_Identity));
        
        string IMigrationMetadata.Id
        {
            get { return "201803180935036_Integrated_ASP.NET_Identity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
